export interface Styliste {
  id: string
  slug: string
  nom: string
  bio: string
  ville: string
  telephone: string
  whatsapp: string
  instagram: string
  photo: string
  nb_tenues: number
  nb_vues: number
  nb_commandes: number
  verified: boolean
}

export interface Tenue {
  id: string
  nom: string
  description: string
  prix: number
  categorie: string
  tailles: string[]
  couleurs: string[]
  photos: string[]
  styliste_id: string
  styliste_nom: string
  styliste_slug: string
  styliste_whatsapp: string
  disponible: boolean
  stock: number
  vues: number
  ville: string
}

export const CATEGORIES = [
  { id: 'boubou', label: 'Boubou', emoji: '👘' },
  { id: 'pagne', label: 'Pagne', emoji: '🧵' },
  { id: 'kaftan', label: 'Kaftan', emoji: '✨' },
  { id: 'dashiki', label: 'Dashiki', emoji: '🦋' },
  { id: 'robe-soiree', label: 'Robe de soirée', emoji: '💫' },
  { id: 'costume', label: 'Costume africain', emoji: '🎩' },
]

export const VILLES = ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey-Calavi', 'Natitingou', 'Abidjan', 'Dakar', 'Lagos']

export const STYLISTES: Styliste[] = [
  {
    id: '1',
    slug: 'adiza-couture',
    nom: 'Adiza Couture',
    bio: 'Styliste de renom depuis 2015, spécialisée dans la haute couture africaine contemporaine. Mes créations mêlent tradition et modernité pour habiller la femme africaine d\'aujourd\'hui.',
    ville: 'Cotonou',
    telephone: '+229 97 12 34 56',
    whatsapp: '22997123456',
    instagram: '@adiza_couture',
    photo: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&q=80',
    nb_tenues: 24,
    nb_vues: 1840,
    nb_commandes: 156,
    verified: true,
  },
  {
    id: '2',
    slug: 'koffi-mode',
    nom: 'Koffi Mode',
    bio: 'Créateur de mode masculine africaine. Costumes sur mesure, boubous brodés et tenues de cérémonies. Chaque pièce est un chef-d\'oeuvre artisanal.',
    ville: 'Porto-Novo',
    telephone: '+229 96 98 76 54',
    whatsapp: '22996987654',
    instagram: '@koffi_mode',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    nb_tenues: 18,
    nb_vues: 1230,
    nb_commandes: 89,
    verified: true,
  },
  {
    id: '3',
    slug: 'aminata-designs',
    nom: 'Aminata Designs',
    bio: 'Passionnée de pagne wax depuis l\'enfance, je transforme les tissus africains en robes de rêve. Mariage, baptême, soirée — je crée pour chaque occasion.',
    ville: 'Abomey-Calavi',
    telephone: '+229 95 44 33 22',
    whatsapp: '22995443322',
    instagram: '@aminata_designs',
    photo: 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=400&q=80',
    nb_tenues: 31,
    nb_vues: 2100,
    nb_commandes: 203,
    verified: false,
  },
  {
    id: '4',
    slug: 'seyni-atelier',
    nom: 'Seyni Atelier',
    bio: 'Atelier de couture dakaroise installé à Parakou. Spécialité : kaftans brodés à la main, dashikis modernes et tenues de mariée africaines.',
    ville: 'Parakou',
    telephone: '+229 98 55 66 77',
    whatsapp: '22998556677',
    instagram: '@seyni_atelier',
    photo: 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=400&q=80',
    nb_tenues: 15,
    nb_vues: 890,
    nb_commandes: 67,
    verified: true,
  },
  {
    id: '5',
    slug: 'grace-fashion',
    nom: 'Grâce Fashion',
    bio: 'La mode africaine revisitée avec une touche contemporaine. Prêt-à-porter et sur mesure pour femmes modernes qui assument leur africanité.',
    ville: 'Cotonou',
    telephone: '+229 97 88 99 00',
    whatsapp: '22997889900',
    instagram: '@grace_fashion_bj',
    photo: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=400&q=80',
    nb_tenues: 42,
    nb_vues: 3200,
    nb_commandes: 287,
    verified: true,
  },
  {
    id: '6',
    slug: 'bako-creation',
    nom: 'Bako Création',
    bio: 'Créateur engagé pour la valorisation du tissu Fon et Yoruba. Collections capsules limitées, chaque pièce raconte une histoire ancestrale.',
    ville: 'Natitingou',
    telephone: '+229 96 11 22 33',
    whatsapp: '22996112233',
    instagram: '@bako_creation',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    nb_tenues: 12,
    nb_vues: 760,
    nb_commandes: 45,
    verified: false,
  },
]

export const TENUES: Tenue[] = [
  {
    id: '1',
    nom: 'Boubou Royal Brodé',
    description: 'Boubou en bazin riche avec broderies dorées à la main. Tenue de prestige pour cérémonies et événements officiels. Tissu importé du Sénégal, travail artisanal béninois.',
    prix: 85000,
    categorie: 'boubou',
    tailles: ['S', 'M', 'L', 'XL', 'XXL'],
    couleurs: ['Blanc cassé', 'Bleu royal', 'Vert forêt'],
    photos: ['https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600&q=80'],
    styliste_id: '1',
    styliste_nom: 'Adiza Couture',
    styliste_slug: 'adiza-couture',
    styliste_whatsapp: '22997123456',
    disponible: true,
    stock: 3,
    vues: 342,
    ville: 'Cotonou',
  },
  {
    id: '2',
    nom: 'Robe Pagne Wax Moderne',
    description: 'Robe élégante taillée dans un pagne wax hollandais authentique. Coupe moderne avec dos ouvert. Parfaite pour soirées et cocktails.',
    prix: 45000,
    categorie: 'pagne',
    tailles: ['XS', 'S', 'M', 'L'],
    couleurs: ['Bleu électrique', 'Orange soleil'],
    photos: ['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?w=600&q=80'],
    styliste_id: '3',
    styliste_nom: 'Aminata Designs',
    styliste_slug: 'aminata-designs',
    styliste_whatsapp: '22995443322',
    disponible: true,
    stock: 5,
    vues: 521,
    ville: 'Abomey-Calavi',
  },
  {
    id: '3',
    nom: 'Kaftan Premium Homme',
    description: 'Kaftan en soie synthétique de haute qualité. Broderies argentées sur col et manches. La tenue idéale pour hommes qui veulent marquer les esprits.',
    prix: 62000,
    categorie: 'kaftan',
    tailles: ['M', 'L', 'XL', 'XXL'],
    couleurs: ['Noir', 'Bordeaux', 'Gris anthracite'],
    photos: ['https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=600&q=80'],
    styliste_id: '2',
    styliste_nom: 'Koffi Mode',
    styliste_slug: 'koffi-mode',
    styliste_whatsapp: '22996987654',
    disponible: true,
    stock: 4,
    vues: 289,
    ville: 'Porto-Novo',
  },
  {
    id: '4',
    nom: 'Dashiki Festival',
    description: 'Dashiki coloré et vibrant, inspiré des motifs Adinkra. Coupe ample et confortable. Parfait pour festivals, sorties et journées décontractées.',
    prix: 22000,
    categorie: 'dashiki',
    tailles: ['S', 'M', 'L', 'XL'],
    couleurs: ['Multicolore', 'Vert/Jaune', 'Rouge/Noir'],
    photos: ['https://images.unsplash.com/photo-1617922001439-4a2e6562f328?w=600&q=80'],
    styliste_id: '4',
    styliste_nom: 'Seyni Atelier',
    styliste_slug: 'seyni-atelier',
    styliste_whatsapp: '22998556677',
    disponible: true,
    stock: 8,
    vues: 178,
    ville: 'Parakou',
  },
  {
    id: '5',
    nom: 'Robe de Mariée Africaine',
    description: 'Robe de mariée alliant tradition africaine et élégance contemporaine. Pagne wax blanc tissé or, traine en mousseline. Sur mesure uniquement.',
    prix: 180000,
    categorie: 'robe-soiree',
    tailles: ['Sur mesure'],
    couleurs: ['Blanc/Or', 'Ivoire/Argent'],
    photos: ['https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=600&q=80'],
    styliste_id: '5',
    styliste_nom: 'Grâce Fashion',
    styliste_slug: 'grace-fashion',
    styliste_whatsapp: '22997889900',
    disponible: true,
    stock: 1,
    vues: 891,
    ville: 'Cotonou',
  },
  {
    id: '6',
    nom: 'Costume 3 Pièces Africain',
    description: 'Costume trois pièces en tissu kente tissé main. Veste, pantalon et gilet. L\'élégance africaine pour vos grandes occasions. Sur commande avec tissu personnalisé.',
    prix: 125000,
    categorie: 'costume',
    tailles: ['M', 'L', 'XL'],
    couleurs: ['Kente classique', 'Kente moderne bleu'],
    photos: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80'],
    styliste_id: '2',
    styliste_nom: 'Koffi Mode',
    styliste_slug: 'koffi-mode',
    styliste_whatsapp: '22996987654',
    disponible: true,
    stock: 2,
    vues: 445,
    ville: 'Porto-Novo',
  },
  {
    id: '7',
    nom: 'Ensemble Pagne Coordonné',
    description: 'Ensemble deux pièces assorti : top et jupe longue en pagne wax hollandais. Idéal pour journées de travail chic et sorties familiales.',
    prix: 38000,
    categorie: 'pagne',
    tailles: ['XS', 'S', 'M', 'L', 'XL'],
    couleurs: ['Bleu/Blanc', 'Jaune/Vert'],
    photos: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80'],
    styliste_id: '1',
    styliste_nom: 'Adiza Couture',
    styliste_slug: 'adiza-couture',
    styliste_whatsapp: '22997123456',
    disponible: true,
    stock: 6,
    vues: 267,
    ville: 'Cotonou',
  },
  {
    id: '8',
    nom: 'Boubou Femme Festif',
    description: 'Grand boubou féminin en bazin léger brodé. Couleurs festives et coupe généreuse. Pour les mariages, baptêmes et fêtes de famille.',
    prix: 55000,
    categorie: 'boubou',
    tailles: ['M', 'L', 'XL', 'XXL'],
    couleurs: ['Rose fuchsia', 'Violet royal', 'Turquoise'],
    photos: ['https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=80'],
    styliste_id: '6',
    styliste_nom: 'Bako Création',
    styliste_slug: 'bako-creation',
    styliste_whatsapp: '22996112233',
    disponible: false,
    stock: 0,
    vues: 134,
    ville: 'Natitingou',
  },
  {
    id: '9',
    nom: 'Kaftan Femme Soirée',
    description: 'Kaftan féminin avec broderies florales. Tissu fluide en crêpe africain. Une silhouette gracieuse pour vos soirées les plus élégantes.',
    prix: 48000,
    categorie: 'kaftan',
    tailles: ['XS', 'S', 'M', 'L'],
    couleurs: ['Emeraude', 'Bleu nuit', 'Or'],
    photos: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80'],
    styliste_id: '3',
    styliste_nom: 'Aminata Designs',
    styliste_slug: 'aminata-designs',
    styliste_whatsapp: '22995443322',
    disponible: true,
    stock: 3,
    vues: 356,
    ville: 'Abomey-Calavi',
  },
  {
    id: '10',
    nom: 'Robe Gala Wax Couture',
    description: 'Robe longue de gala en pagne wax couture. Décolleté sophistiqué, fente élégante, traîne courte. La reine de toutes les soirées.',
    prix: 95000,
    categorie: 'robe-soiree',
    tailles: ['XS', 'S', 'M', 'L'],
    couleurs: ['Rouge flamme', 'Noir profond'],
    photos: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80'],
    styliste_id: '5',
    styliste_nom: 'Grâce Fashion',
    styliste_slug: 'grace-fashion',
    styliste_whatsapp: '22997889900',
    disponible: true,
    stock: 2,
    vues: 712,
    ville: 'Cotonou',
  },
  {
    id: '11',
    nom: 'Dashiki Business Casual',
    description: 'Dashiki revisité pour le bureau. Coupe structurée, tissu premium. Alliez style africain et professionnalisme au quotidien.',
    prix: 32000,
    categorie: 'dashiki',
    tailles: ['S', 'M', 'L', 'XL', 'XXL'],
    couleurs: ['Bleu marine', 'Gris', 'Beige'],
    photos: ['https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80'],
    styliste_id: '4',
    styliste_nom: 'Seyni Atelier',
    styliste_slug: 'seyni-atelier',
    styliste_whatsapp: '22998556677',
    disponible: true,
    stock: 7,
    vues: 203,
    ville: 'Parakou',
  },
  {
    id: '12',
    nom: 'Grand Boubou Cérémonie',
    description: 'Boubou de cérémonie richement brodé, parfait pour les grandes occasions. Tissu damassé avec liseré or. Un habit de roi pour les hommes de prestige.',
    prix: 110000,
    categorie: 'boubou',
    tailles: ['L', 'XL', 'XXL', 'XXXL'],
    couleurs: ['Blanc/Or', 'Bleu/Argent', 'Vert/Or'],
    photos: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80'],
    styliste_id: '6',
    styliste_nom: 'Bako Création',
    styliste_slug: 'bako-creation',
    styliste_whatsapp: '22996112233',
    disponible: true,
    stock: 1,
    vues: 189,
    ville: 'Natitingou',
  },
]
